const data = [
    {"Id": 1, "Address": "Medical Officer Incharge, ESI Dispensary, C-235, Model Town-III, Azadpur, DELHI", "Location": "Azadpur"},
    {"Id": 2, "Address": "Near Vardhman Mall, Sec 7 Dwarka New delhi", "Location": "Dwarka - Sector-7"},
    {"Id": 3, "Address": "JAHANGIRPURI BADLI EXTENSION A-79,Badli Extension, Outer Ring Road, New Delhi", "Location": "Badli Extension"},
    {"Id": 4, "Address": "JAWALAPURI Resettlement Colony, Phase-4,Jawalapuri, New Delhi", "Location": "Jawala Puri"},
    {"Id": 5, "Address": "MADIPUR Pocket-03, Paschim Vihar, Madipur, New Delhi", "Location": "Madipur"},
    {"Id": 6, "Address": "MANGOLPURI Block-O, Mangolpuri, New Delhi", "Location": "Mangolpuri"},
    {"Id": 7, "Address": "NARELA U-103, Vijay Nagar, Narela, New Delhi", "Location": "Narela"},
    {"Id": 8, "Address": "WAZIRPUR Block-A, Wazirpur Industrial Area, Behind Richi Rich Restaurant, New Delhi", "Location": "Wazirpur"},
    {"Id": 9, "Address": "2C-35 C Block, Model Town III, Delhi", "Location": "Model Town"},
    {"Id": 10, "Address": "Sarojini Nagar opp Sarojini Nagar DTC Bus Deport", "Location": "Sarojini Nagar"},
    {"Id": 11, "Address": "I-Block, Karampura,New Delhi", "Location": "Karampura"},
    {"Id": 12, "Address": "Behind Choti masjid Near Inderlok Metro Station Inderlok, Delhi 110014", "Location": "Inderlok"},
    {"Id": 13, "Address": "A-79, Outer Ring Road, Badli Extention, Delhi 110042", "Location": "Badli Extension"},
    {"Id": 14, "Address": "Opp. Lajpat Nagar Railway Crossing New Delhi 110014", "Location": "Lajpat Nagar"},
    {"Id": 15, "Address": "Resettlement Colony, Phase IV, Jwalapuri , Nangloi, New Delhi", "Location": "Nangloi"},
    {"Id": 16, "Address": "G Block, Opposite CGHS Despensary Near Deshbandhu College Kalkaji, New Delhi 110019", "Location": "Kalka Ji"},
    {"Id": 17, "Address": "Pocket-III, Paschim Puri, Madipur New Delhi 110063", "Location": "Madipur"},
    {"Id": 18, "Address": "O-Block, Near Water Tank Mangol Puri, New Delhi 110083", "Location": "Magol Puri"},
    {"Id": 19, "Address": "B-309 DDA Shopping centre ESI Dispansary Mayapuri 1 New Delhi 110064", "Location": "Mayapuri"},
    {"Id": 20, "Address": "D-22, Facility Centre Near Punjab Sind Bank Mayapuri-2 New Delhi 110064", "Location": "Mayapuri"},
    {"Id": 21, "Address": "183 A 183 B 184 A 184 B DDa Flats Mayur Vihar Phase I New Delhi 110091", "Location": "Mayur Vihar"},
    {"Id": 22, "Address": "33 B-79 Kishangarh, VasantKunj New Delhi 110070", "Location": "Vasant Kunj"},
    {"Id": 23, "Address": "Mori Gate Near Tis Hazari Court New Delhi 110006", "Location": "Mori Gate"},
    {"Id": 24, "Address": "1625-C2, Thana Road, Najafgarh, New delhi 110043", "Location": "Najafgarh"},
    {"Id": 25, "Address": "ESIC Dispensary Nand Nagri Near DTC Bus Depo New Delhi 110093", "Location": "Nand Nagri"},
    {"Id": 26, "Address": "U-103, Vijay nagar, Near Police Station Narela New delhi 110040", "Location": "Narela"},
    {"Id": 27, "Address": "NIA-I Karampura Near Moti Nagar Police Station", "Location": "Moti Nagar"},
    {"Id": 28, "Address": "DSIDC Sheds, Okhla Industrial Area, New Delhi 110020", "Location": "Okhla"},
    {"Id": 29, "Address": "Building No. 1880, Gno-10-11, Gurudwara Road Paharganj New Delhi 110055", "Location": "Paharganj"},
    {"Id": 30, "Address": "Tagore Garden Extension, Near Holy Child School New Delhi 110027", "Location": "Tagore Garden"},
    {"Id": 31, "Address": "Pocket B-9, Rohini Sec-5, New Delhi 110085", "Location": "Rohini - Sector-5"},
    {"Id": 32, "Address": "Welcome Colony Phase-4 Seelampur New delhi 110053", "Location": "Seelampur"},
    {"Id": 33, "Address": "Shastri Nagar near Shastri nagar Metro Station Vivekanandpuri New Delhi", "Location": "Shastri Nagar"},
    {"Id": 34, "Address": "154 Shaktinagar, Nagia Park Behind Birla Mill New delhi 110007", "Location": "Shakti Nagar"},
    {"Id": 35, "Address": "Tigri, Behind State Bank Of India, Ambedkar Nagar sector-1, Tigri New Delhi 110080", "Location": "Ambedkar Nagar - Sector-1"},
    {"Id": 36, "Address": "Tilak Vihar, Near Tilak Vihar Police Chowki, New Delhi 110018", "Location": "Tilak Vihar"},
    {"Id": 37, "Address": "HN 181-184, 186-191 Labour Colony, VK nagar", "Location": "V K Nagar"},
    {"Id": 38, "Address": "A-Block, Industrial Area Wazirpur New Delhi", "Location": "Wazirpur"},
    {"Id": 39, "Address": "BADLI EXTENSION A-79, Badli Extension, Outer Ring Road, DELHI", "Location": "Outer Ring Road"},
    {"Id": 40, "Address": "JAWALA PURI, ESI Dispensary Resettlement Colony, Phase-4, Jawala Puri, DELHI", "Location": "Jawala Puri"},
    {"Id": 41, "Address": "MANGOLPURI, ESI Dispensary O-Block, Mangolpuri, DELHI-83", "Location": "Mangolpuri"},
    {"Id": 42, "Address": "NARELA, ESI Dispensary House No. 70, Panna Udyan, Railway Road, Narela DELHI", "Location": "Narela"},
    {"Id": 43, "Address": "ROHINI SEC-V, ESI Dispensary Pocket B-9, Sector-V Rohini DELHI", "Location": "Rohini - Sector-5"},
    {"Id": 44, "Address": "WAZIRPUR, ESI Dispensary A-Block Wazirpur Indl. Area Behind Richi Rich Restaurant, Delhi", "Location": "Wazirpur"},
    {"Id": 45, "Address": "ESI DISPENSARY DWARKA, Near Vardhman Mall, Sec 7 Dwarka New delhi", "Location": "Dwarka - Sector-7"},
    {"Id": 46, "Address": "ESI DISPENSARY FECTORY ROAD, SAROJINI NAGAR, Sarojini Nagar opp Sarojini Nagar DTC Bus Deport", "Location": "Sarojini Nagar"},
    {"Id": 47, "Address": "ESI DISPENSARY KALKAJI, G Block, Opposite CGHS Despensary Near Deshbandhu College Kalkaji, New Delhi 110019", "Location": "Kalka Ji"},
    {"Id": 48, "Address": "ESI DISPENSARY, 33 B-79 Kishangarh, VasantKunj New Delhi 110070", "Location": "Vasant Kunj"},
    {"Id": 49, "Address": "ESI DISPENSARY, DSIDC Sheds, Okhla Industrial Area, New Delhi 110020", "Location": "Okhla"},
    {"Id": 50, "Address": "ESI DISPENSARY, Tigri, Behind State Bank Of India, Ambedkar Nagar sector-1, Tigri New Delhi 110080", "Location": "Ambedkar Nagar - Sector-1"}
]


